export const messages = {
  en: {
    connect:{
      title:"Connect To Server",
      name:"Connection Name",
      scope:"Connection Scope",
      success:"Success!",
      error:"Connection error!",
      global:"Global",
      current:"Current Workspace",
      connecting:"Connect",
      close:"Close",
      sshTunnel:"SSH Tunnel",
      connectTimeout:"Connect Timeout",
      requestTimeout:"Request Timeout",
      useSSL:"Use SSL",
    },
    config:{
      serverType:"Server Type",
      host:"Host",
      port:"Port",
      username:"Username",
      password:"Password",
      database:"Database",
      showedDatabases:"Showed Databases",
      timeZone:"Time Zone",
    },
    result:{
      export:"Export",
      exportOption:"Export Option",
      exportType:"Export Type",
      removeLimit:"Remove Limit",
      cancel:"Cancel",
      searchNotice:"Input To Search Data",
      deleteNotice:"You need to select at least one row of data!",
      cost:"Cost",
      copy:"Copy",
      editDialog:"Open Edit Dialog",
      copyDialog:"Open Copy Dialog",
    }
  },
  "zh-cn": {
    connect:{
      title:"连接至服务器",
      name:"连接名称",
      scope:"连接作用范围",
      success:"连接成功!",
      error:"连接出错!",
      global:"全局",
      current:"当前工作空间",
      connecting:"连接",
      close:"关闭",
      sshTunnel:"SSH隧道",
      connectTimeout:"连接超时",
      requestTimeout:"请求超时",
      useSSL:"使用SSL",
    },
    config:{
      serverType:"服务器类型",
      host:"主机名",
      port:"端口",
      username:"用户名",
      password:"密码",
      database:"数据库",
      showedDatabases:"显示的数据库",
      timeZone:"时区",
    },
    result:{
      export:"导出",
      exportOption:"导出选项",
      exportType:"导出类型",
      removeLimit:"移除Limit",
      cancel:"取消",
      searchNotice:"输入以搜索数据",
      deleteNotice:"你需要选择至少一条数据!",
      cost:"耗时",
      copy:"复制",
      editDialog:"打开编辑窗",
      copyDialog:"打开复制窗",
    }
  }
}

