name: CI
on:
  push:
    branches: [ master,webpack ]
  pull_request:
    branches: [ master,webpack ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm i
    - run: |
        echo ">>> Start compile vscode-mysql."
        npm run build
        echo ">>> Compile vscode-mysql sucess!"
